---
# handlers file for iscsi_lnx_1

- name: restart ntp
  service: name=ntpd state=restarted

- name: restart iptables
  service: name=iptables state=restarted
  
- name: restart apache
  service: name=httpd state=restarted
  
- name: restart memcached
  service: name=memcached state=restarted
  
- name: make sure apache is running
  service: name=httpd state=running

- name: restart iscsid
  service: name=iscsid state=restarted
